### ISSUE TITLE
Pager should not be visible if there is only one page

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#11]
It would be better if the pager buttons and text would be visible only if there are more than one page:

![image](https://cloud.githubusercontent.com/assets/6435556/10629796/451bb9b4-77d2-11e5-9ef9-d55411521b68.png)

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Pages does not appear automatically when number of rows exceed one page.

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Not fixed.

Steps to reproduce:

1. Open `/invoicedemo/new-invoice` page
2. Press Add row button ten times.
3. Nine rows will be added, on the tenth click the rows will disappear.

**Comment by jakubklekota** [comment]
>Nine rows will be added, on the tenth click the rows will disappear.

Sorry, but I don't understand your idea. Can you explain me more ?

**Comment by miyconst** [comment]
Just follow the steps I provided.

If I create more than ten invoice rows in a new invoice (not saved), then it looks like switching to new page, but the pager is not visible.

**Comment by krzysztofspilka** [comment]
@miyconst I tested it today following the steps provided and couldn't find the issue (on the tenth click the table is being paginated to page 2 starting from row 11):

![image](https://cloud.githubusercontent.com/assets/8048526/11741587/48d79c6c-9ffa-11e5-9a17-6e100bb4385e.png)

Could you confirm that you see what I see? Maybe there's a problem somewhere else, we test different version etc.

**Comment by miyconst** [comment]
Yes.. I do confirm. 

Don't know what the issue was, but after I have created a couple invoices it's gone.
Maybe some browser cache, though I did clear it.

Thanks for testing.

I close the issue for now, will open it again, when find how to reproduce it.
