### ISSUE TITLE
Limit per page should be visible only if there are more than 10 rows

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#12]
It would be better if the limit per page select and text would be visible only if there are more than 10 rows:

![image](https://cloud.githubusercontent.com/assets/6435556/10629822/725dac02-77d2-11e5-858f-a7453c3efc38.png)

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Not fixed. 

Steps to reproduce:

1. Create new invoice.
2. Save it.
3. Navigate to it.
4. Create 11 rows.
5. Select `Limit per page: 25`.
6. The Limit per page section disappears.

**Comment by krzysztofspilka** [comment]
@jakubklekota The select should appear if there're more than 10 rows and I still can see it when having just 10 rows.

**Comment by jakubklekota** [comment]
OK, repaired
