### ISSUE TITLE
JavaScript variables and functions should not be in window scope

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#15]
On this page JavaScript variables and functions are in window scope:
https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L91

The functions are used like this:
https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L42

This won't work if some other application would also define a variable `var tpl` or `function chooseLimitDisplay`. All of such values should be defined in `<template is="dom-bind">` scope.

Example:

```js
(function () {
	var tpl = (document._currentScript || document.currentScript).previousElementSibling;

	tpl.chooseLimitDisplay = function (e) {
		tpl.set("model.Pagination.RowsPage$", e.target.value);
	};
})();
```

```html
<select id="limit-per-page" on-change="chooseLimitDisplay">
```

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Why would you need two variables for same element?

https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L96
https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L105

**Comment by jakubklekota** [comment]
Oh, I have not noticed

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Not fixed.

The `tpl` variable is never declared:

https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L109

https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L116

**Comment by jakubklekota** [comment]
Try again

**Comment by miyconst** [comment]
Again a function in windows scope:

https://github.com/handsoncode-apps/InvoiceDemo/blob/master/wwwroot/InvoiceDemo/InvoiceDetailsPage.html#L152

**Comment by jakubklekota** [comment]
@miyconst Yes, because is function for ```Restore table ``` button, which fire ```RestoreState()``` function

It's wrong ?

**Comment by miyconst** [comment]
Yes, it's wrong. In Starcounter you never know what other applications are running and what functions they define. You should not define any global functions and variables.

**Comment by jakubklekota** [comment]
Now I understood

**Comment by miyconst** [comment]
Okay, closing this issue, but this one is related: https://github.com/handsoncode-apps/InvoiceDemo/issues/31
