### ISSUE TITLE
Add possibility to change column order by dragging

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#20]

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Add row button restores columns original position.

**Comment by krzysztofspilka** [comment]
@jakubklekota "Add row button restores columns original position." - true, still reproducible. It that connected with #18?
