### ISSUE TITLE
Changing value of Good/Service column results in 5-10 seconds hang

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#25]
Steps to reproduce:

1. Create new invoice.
2. Create about 20 invoice rows.
3. Click on any cell in the Good/Service column.
4. Input any value.
5. Press enter.

Browser hangs for about 5-10 seconds, CPU usage rises for about 10% (e3-1230v3).

**Comment by jakubklekota** [comment]
fixed

**Comment by miyconst** [comment]
Not fixed.

Steps to reproduce:

1. Open `/invoicedemo/new-invoice`.
2. Create nine more rows.
3. Place cursor to the first cell of the first column.
4. Fill value and press enter.
5. Do same for all rows.
6. Do same for all columns.
7. As more values entered as slower response is.

**Comment by jakubklekota** [comment]
@miyconst can you reproduce it ?

**Comment by miyconst** [comment]
Seems to be fixed now. Closing the issue.
